---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  workflows:
    uses: erdnaxela02/ha-addon-workflows/.github/workflows/addon-ci.yaml@main
