---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/pr-labels.yaml@main
