---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/pr-labels.yaml@1ece86bb34605edfed3a242a263acd818cc546cb # main
